from django.urls import path
from . views import *

urlpatterns = [
    # Home
    path('', home_view, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('admission/', admission, name='admission'),
    path('logout/', logout_view, name='logout'),
    # Admin
    path('register_approvals/', register_approvals, name='register_approval'),
    path('admission_messages/', admission_messages, name='admission_messages'),
    path('contact_messages/', contact_messages, name='contact_messages'),
    path('approve_user/<int:user_id>/<str:user_type>/', approve_user, name='approve_user'),
    path('reject_user/<int:user_id>/<str:user_type>/', reject_user, name='reject_user'),
    path('classes/', classes, name='classes'),
    path('classes/update/<int:class_id>/', update_class, name='update_class'),
    path('delete_class/<int:class_id>/', delete_class, name='delete_class'),
    path('sections/', sections, name='sections'),
    path('update_sections/', update_sections, name='update_sections'),
    path('delete_sections/', delete_sections, name='delete_sections'), 
    path('subjects/', subjects, name='subjects'),
    path('update_subjects/', update_subjects, name='update_subjects'),
    path('delete_subjects/', delete_subjects, name='delete_subjects'), 
    path('exam/', exam, name='exam'),
    path('departments/', departments, name='departments'),
    path('edit_department/<int:department_id>/', edit_department, name='edit_department'),
    path('academic_session/', academic_session, name='academic_session'),
    path('employee_category/', employee_category, name='employee_category'),
    path('leave_approval/', leave_approval, name='leave_approval'),
    path('update_leave_approval/<int:pk>/<str:status>/', update_leave_approval, name='update_leave_approval'),
    path('fees/', fees, name='fees'),
    path('fees_payment/', fees_payment, name='fees_payment'),
    path('salary_payment/', salary_payment, name='salary_payment'),
    path('busroute/', busroute, name='busroute'),
    path('send_sms/', send_sms, name='send_sms'),
    path('attendance/', attendance, name='attendance'),
    path('timetable/', timetable, name='timetable'),
    # Staff
    path('staff-dashboard/', staff_portal, name='staff_portal'),
    path('staff_attendance/', staff_attendance, name='staff_attendance'),
    path('staff_timetable/', staff_timetable, name='staff_timetable'),
    path('staff_leave_request/', staff_leave_request, name='staff_leave_request'),
    path('staff_payslip/', staff_payslip, name='staff_payslip'),
    path('staff_bus/', staff_bus_details, name='staff_bus'),
    # Faculty
    path('faculty-dashboard/', faculty_portal, name='faculty_portal'),
    path('faculty_attendance/', faculty_attendance, name='faculty_attendance'),
    path('leave_request/', leave_request, name='leave_request'),
    path('faculty_timetable/', faculty_timetable, name='faculty_timetable'),
    path('faculty_payslip/', faculty_payslip, name='faculty_payslip'),
    path('marks/', marks, name='marks'),
    path('faculty_bus/', faculty_bus_details, name='faculty_bus'),
    # Student
    path('student_dashboard/', student_portal, name='student_portal'),
    path('student_classes/', student_classes, name='student_classes'),
    path('student_attendance/', student_attendance, name='student_attendance'),
    path('student_timetable/', student_timetable, name='student_timetable'),
    path('exam_timetable/', exam_timetable, name='exam_timetable'),
    path('student_marks/', student_marks, name='student_marks'),
    # Parent
    path('parent-dashboard/', parent_portal, name='parent_portal'),
    path('parent_classes/', parent_classes, name='parent_classes'),
    path('parent_attendance/', parent_attendance, name='parent_attendance'),
    path('parent_timetable/', parent_timetable, name='parent_timetable'),
    path('parent_exam_timetable/', parent_exam_timetable, name='parent_exam_timetable'),
    path('parent_marks/', parent_marks, name='parent_marks'),
    path('parent_fees/', parent_fees, name='parent_fees'),
    path('create_order/', create_order, name='create_order'),
    path('paytm/callback/', payment_callback, name='payment_callback'),
    path('parent_bus/', parent_bus_details, name='parent_bus'),

    
]
