# Generated by Django 4.2.10 on 2024-08-01 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BusFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=25)),
                ('bus_number', models.CharField(max_length=10)),
                ('driver_name', models.CharField(max_length=25)),
                ('driver_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('location', models.CharField(default=None, max_length=25, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('class_assigned', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.class')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='faculty_attendance/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('faculty_leaves', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MessFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.class')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('location', models.CharField(default=None, max_length=25, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='staff_attendance/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('staff_leaves', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TuitionFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_linked', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=100, null=True)),
                ('class_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.class')),
                ('section_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.section')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_timetable/')),
                ('class_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.class')),
                ('section_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.section')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('roll_number', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(default=None, max_length=25, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('class_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.class')),
                ('section_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.section')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_attendance/')),
                ('date', models.DateField(auto_now_add=True)),
                ('class_assigned', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.class')),
                ('faculty', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.faculty')),
                ('section_assigned', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.section')),
            ],
        ),
        migrations.CreateModel(
            name='StaffTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='staff_timetable/')),
                ('staff', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='staff_payslips/')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('bus_route', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_locations', to='sms.busroute')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Demand Draft', 'Demand Draft'), ('Cheque', 'Cheque')], default=None, max_length=20, null=True)),
                ('fees_type', models.CharField(choices=[('Bus Fees', 'Bus Fees'), ('Mess Fees', 'Mess Fees'), ('Tuition Fees', 'Tuition Fees')], default=None, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('receipt_number', models.CharField(max_length=20)),
                ('class_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.class')),
                ('section_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.section')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.students')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_name', models.CharField(max_length=25)),
                ('contact_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('children', models.ManyToManyField(to='sms.students')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Annual', 'Annual'), ('Unit Test', 'Unit Test')], max_length=20)),
                ('unit_test_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='student_marks/')),
                ('class_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.class')),
                ('faculty', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.faculty')),
                ('section_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.section')),
                ('subject', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=10)),
                ('leave_type', models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave')], default=None, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_changed', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='faculty_timetable/')),
                ('faculty', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FacultySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='faculty_payslips/')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='section_assigned',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.section'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Annual', 'Annual'), ('Unit Test', 'Unit Test')], max_length=20)),
                ('unit_test_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='exam_timetable/')),
                ('class_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.class')),
                ('section_linked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.section')),
            ],
        ),
        migrations.CreateModel(
            name='DropoffLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('bus_route', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_locations', to='sms.busroute')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.ManyToManyField(related_name='departments', to='sms.faculty')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('class_assigned', 'section_assigned')},
        ),
    ]
