# Generated by Django 4.2.10 on 2024-08-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_payment_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('class_of_admission', models.CharField(max_length=10)),
                ('previous_school', models.CharField(max_length=30)),
                ('parent_name', models.CharField(max_length=30)),
                ('parent_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
