# Generated by Django 4.2.10 on 2024-08-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_studentadmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAdmission',
        ),
    ]
